apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"apricot","namespace":"pineapple"},"spec":{"containers":[{"image":"nginx","name":"banana-boat"}]}}
  creationTimestamp: "2023-08-18T20:39:39Z"
  name: apricot
  namespace: banana
  resourceVersion: "381289"
  uid: 519f74c0-cbdb-43d7-ade7-452eaceb5e88
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: banana-boat
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hc69f
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node-1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-hc69f
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-18T20:39:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-18T20:39:40Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-18T20:39:40Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-18T20:39:39Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://a2460c74640820f5ac5cc33eeb5d0275b7435008912d7953a775433cc42ce61a
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:104c7c5c54f2685f0f46f3be607ce60da7085da3eaa5ad22d3d9f01594295e9c
    lastState: {}
    name: banana-boat
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-08-18T20:39:40Z"
  hostIP: 10.12.223.1
  phase: Running
  podIP: 192.168.84.171
  podIPs:
  - ip: 192.168.84.171
  qosClass: BestEffort
  startTime: "2023-08-18T20:39:39Z"
