apiVersion: v1
kind: Pod
metadata:
  name: singer        # name to apply
  namespace: talent
spec:
  containers:
  - name: opera        # name of container
    image: nginx:1.7.9       # image to use if no URL provided hub.docker.com is used
    ports:
      - name: web
        containerPort: 80      # access on this port (int)

