---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-configured
spec:
  containers:
  - name: nginx
    image: nginx:1.18.0
    ports:
    - containerPort: 80
    volumeMounts: 
    - name: garfield
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: odie
      mountPath: /var/www/index.html
      subPath: index.html
    - name: john
      mountPath: /var/www/static/nginx.txt
      subPath: nginx.txt
  volumes:
  - name: garfield
    configMap:
      name: nginx-conf 
  - name: odie
    configMap:
      name: index-file 
  - name: john
    configMap:
      name: nginx-txt